/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesPlanillero;
import Conexion.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import cristorey_ef.Documento;
import cristorey_ef.PaqueteTuristico;
import cristorey_ef.PaqueteTuristicoControlador;
import cristorey_ef.Pasajero;
import cristorey_ef.PasajeroControlador;
import cristorey_ef.ReservaControlador;
import java.awt.Color;
import java.awt.Component;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class RegistroPasajero extends javax.swing.JPanel {

    /**
     * Creates new form RegistroPasajero
     */
    DateTimeFormatter formatoFechaLocal = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private PasajeroControlador pc;
    private ReservaControlador rc;
    private PaqueteTuristicoControlador ptc;
    public RegistroPasajero(PasajeroControlador pc, ReservaControlador rc, PaqueteTuristicoControlador ptc) {
        initComponents();
        this.pc = pc;
        this.rc = rc;
        this.ptc = ptc;
        cargarPaquetes();
        actualizarInfoCupos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApMaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApPaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxTipoDoc = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbxResidencia = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFechaVencimiento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        btnValidarDocumento = new javax.swing.JButton();
        lblVigencia = new javax.swing.JLabel();
        txtFechaEmision = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblCupos = new javax.swing.JLabel();
        btnAsignarPaquete = new javax.swing.JButton();
        cbxPaquete = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 249, 236));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 164, 61), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(328, 366));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Pasajeros.png"))); // NOI18N
        jLabel1.setText("DATOS PERSONALES");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nombre");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Ap. Materno");

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Ap. Paterno");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Telefono");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Correo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(txtApPaterno)
                            .addComponent(txtApMaterno)
                            .addComponent(txtTelefono)
                            .addComponent(txtCorreo))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 53, 0, 0);
        jPanel4.add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 164, 61), 2));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/id-insignia.png"))); // NOI18N
        jLabel7.setText("DOCUMENTO DE INDENTIDAD");

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Tipo");

        cbxTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "CE" }));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Residencia");

        cbxResidencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Extranjero" }));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("N° de documento");

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("F. emisión");

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("F. vencimientod");

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Edad");

        btnValidarDocumento.setText("Validad documento");
        btnValidarDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 164, 61)));
        btnValidarDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValidarDocumento.addActionListener(this::btnValidarDocumentoActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(cbxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(cbxResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(92, 92, 92)
                            .addComponent(jLabel12))
                        .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel13)
                        .addComponent(lblVigencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnValidarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaVencimiento)
                    .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnValidarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 41, 0, 0);
        jPanel4.add(jPanel2, gridBagConstraints);

        btnRegistrar.setBackground(new java.awt.Color(255, 189, 105));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar pasajero");
        btnRegistrar.setBorder(null);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 289, 0, 0);
        jPanel4.add(btnRegistrar, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 170, 44), 2));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/viaje-en-coche.png"))); // NOI18N
        jLabel18.setText("ASIGNACIÓN A PAQUETE TURÍSTICO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 20, 0, 0);
        jPanel3.add(jLabel18, gridBagConstraints);

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Paquete turístico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 20, 0, 0);
        jPanel3.add(jLabel19, gridBagConstraints);

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Cupos disponibles");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 44, 0, 0);
        jPanel3.add(jLabel20, gridBagConstraints);

        lblCupos.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblCupos.setForeground(new java.awt.Color(80, 50, 22));
        lblCupos.setText("-- / --");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 18, 0, 71);
        jPanel3.add(lblCupos, gridBagConstraints);

        btnAsignarPaquete.setBackground(new java.awt.Color(255, 189, 105));
        btnAsignarPaquete.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAsignarPaquete.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarPaquete.setText("Asignar a paquete");
        btnAsignarPaquete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsignarPaquete.addActionListener(this::btnAsignarPaqueteActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 323;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 97, 13, 0);
        jPanel3.add(btnAsignarPaquete, gridBagConstraints);

        cbxPaquete.addActionListener(this::cbxPaqueteActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        jPanel3.add(cbxPaquete, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 21, 0, 42);
        jPanel4.add(jPanel3, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(80, 50, 22));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/registroPasajero.png"))); // NOI18N
        jLabel17.setText("Registro de pasajeros");

        btnLimpiar.setBackground(new java.awt.Color(255, 189, 105));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(17, 17, 17))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private Documento obtenerDocumento() {

        try {
            
            LocalDate fechaEmision = LocalDate.parse(txtFechaEmision.getText().trim(),formatoFechaLocal);
            LocalDate fechaVencimiento = LocalDate.parse(txtFechaVencimiento.getText().trim(),formatoFechaLocal);
            int edad = Integer.parseInt(txtEdad.getText().trim());

            return new Documento(
                    cbxTipoDoc.getSelectedItem().toString(),
                    txtNumDoc.getText().trim(),
                    fechaEmision,
                    fechaVencimiento,
                    cbxResidencia.getSelectedItem().toString(),
                    edad
            );

        } catch (DateTimeParseException ex) {

            mostrarError("Formato de fecha inválido\n Usa dd/MM/yyyy");

        } catch (NumberFormatException ex) {

            mostrarError("La edad debe contener solo números");

        }
        return null;

    }
    private boolean camposDocumentoCompletos() {

        if (txtNumDoc.getText().trim().isEmpty()) {
            mostrarError("Ingrese el número de documento");
            txtNumDoc.requestFocus();
            return false;
        }

        if (txtFechaEmision.getText().trim().isEmpty()) {
            mostrarError("Ingrese la fecha de emisión");
            txtFechaEmision.requestFocus();
            return false;
        }

        if (txtFechaVencimiento.getText().trim().isEmpty()) {
            mostrarError("Ingrese la fecha de vencimiento");
            txtFechaVencimiento.requestFocus();
            return false;
        }

        if (txtEdad.getText().trim().isEmpty()) {
            mostrarError("Ingrese la edad");
            txtEdad.requestFocus();
            return false;
        }

        return true;
    }
    private boolean camposPasajeroCompletos() {

        if (txtNombre.getText().trim().isEmpty()) {
            mostrarError("Ingrese el nombre");
            txtNombre.requestFocus();
            return false;
        }

        if (txtApPaterno.getText().trim().isEmpty()) {
            mostrarError("Ingrese el apellido paterno");
            txtApPaterno.requestFocus();
            return false;
        }
        
        if (txtApMaterno.getText().trim().isEmpty()) {
            mostrarError("Ingrese el apellido materno");
            txtApMaterno.requestFocus();
            return false;
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            mostrarError("Ingrese el número de telefono");
            txtTelefono.requestFocus();
            return false;
        }

        if (txtCorreo.getText().trim().isEmpty()) {
            mostrarError("Ingrese el correo");
            txtCorreo.requestFocus();
            return false;
        }

        return true;
    }
    
    private void cargarPaquetes() {
        
            javax.swing.DefaultComboBoxModel<PaqueteTuristico> modelo = new javax.swing.DefaultComboBoxModel<>();

    try (Connection con = ConexionBD.conectar()) {

        if (con == null) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo conectar a la base de datos.",
                    "Error de conexión", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(
            "SELECT codigo_paquete, nombre_paquete, destino, costo, horario, "
            + "cupos_maximos, cupos_disponibles FROM PaqueteTuristico"
        );

        while (rs.next()) {
            PaqueteTuristico paq = new PaqueteTuristico(
                rs.getString("nombre_paquete"),
                rs.getString("codigo_paquete"),
                rs.getString("destino"),
                rs.getDouble("costo"),
                rs.getString("horario"),
                rs.getInt("cupos_maximos"),
                rs.getInt("cupos_disponibles")
            );
            modelo.addElement(paq);
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Error al cargar los paquetes:\n" + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }

    cbxPaquete.setModel(modelo);
    cbxPaquete.setRenderer(new DefaultListCellRenderer() {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value instanceof PaqueteTuristico) {
                PaqueteTuristico paq = (PaqueteTuristico) value;
                setText(paq.getNombre_paquete());
            }
            return this;
        }
    });
}
      
    private void actualizarInfoCupos() {
        PaqueteTuristico paquete = (PaqueteTuristico) cbxPaquete.getSelectedItem(); 
        
         if (paquete == null) {
            lblCupos.setText("-- / --");
            return;
        }
        
        lblCupos.setText(paquete.getCupos_disponibles() + " / " + paquete.getCupos_maximos());
        
        if (paquete.tieneCupos()) {
            lblCupos.setForeground(new Color(27, 94, 32));
        } else {
             lblCupos.setForeground(new Color(127, 16, 16));
        }
    }
    
    private void limpiarFormulario() {
        txtNombre.setText("");  txtApPaterno.setText("");  txtApMaterno.setText("");
        txtTelefono.setText(""); txtCorreo.setText("");
        txtNumDoc.setText("");   txtFechaEmision.setText(""); txtFechaVencimiento.setText("");
        txtEdad.setText("");
        cbxTipoDoc.setSelectedIndex(0);
        cbxResidencia.setSelectedIndex(0);
        lblVigencia.setText("");
        lblVigencia.setOpaque(false);
        lblVigencia.repaint();
        btnRegistrar.setEnabled(false);
    }

    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    
    private void btnValidarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarDocumentoActionPerformed
        // TODO add your handling code here:
        if (!camposDocumentoCompletos()) {
            return;
        }

        Documento doc = obtenerDocumento();
        if (doc == null) {
            return;
        }
        
        if (!doc.numDocValido()) {
            if (doc.getTipo_doc().equals("DNI")) {

                mostrarError("El DNI debe contener exactamente 8 dígitos");

            } else {

                mostrarError("El Carné de Extranjería debe contener exactamente 9 dígitos");

            }
            return;
        }

        if (!doc.edadValida()) {
            mostrarError("La edad debe estar entre 1 y 110 años");
            return;
        }
        
        lblVigencia.setOpaque(true);
        
        if (doc.validarVigencia()) {
            lblVigencia.setText("No caduca");
            lblVigencia.setForeground(new Color(69, 39, 160));
            lblVigencia.setBackground(new Color(237, 231, 246));
            btnRegistrar.setEnabled(true);
        } else if (doc.documentoVigente()) {
            lblVigencia.setText("Documento VIGENTE");
            lblVigencia.setForeground(new Color(27, 94, 32));
            lblVigencia.setBackground(new Color(232, 245, 233));
            btnRegistrar.setEnabled(true);
        } else {
            lblVigencia.setText("Documento VENCIDO — No se puede registrar");
            lblVigencia.setForeground(new Color(127, 16, 16));
            lblVigencia.setBackground(new Color(255, 235, 238));
            btnRegistrar.setEnabled(false);
        }
        
        lblVigencia.revalidate();
        lblVigencia.repaint();
    }//GEN-LAST:event_btnValidarDocumentoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
            if (!camposPasajeroCompletos()) {
        return;
    }
    String nroDoc = txtNumDoc.getText().trim();

    if (pc.buscarDocumento(nroDoc) != null) {
        mostrarError("Ya existe un pasajero registrado con el N° de documento " + nroDoc + "Reinscripción detectada");
        return;
    }

    Documento doc = obtenerDocumento();

    if (doc == null || !doc.documentoVigente()) {
        mostrarError("Debe validar primero el documento");
        return;
    }

    Pasajero pasajero = new Pasajero(
        txtApPaterno.getText().trim(),
        txtApMaterno.getText().trim(),
        txtNombre.getText().trim(),
        txtTelefono.getText().trim(),
        txtCorreo.getText().trim(),
        doc
    );
    if (!pasajero.numTelefonoValido()) {
        mostrarError("El número de teléfono debe tener exactamente 9 dígitos");
        return;
    }

    pc.registrarPasajero(pasajero);

    try (Connection con = ConexionBD.conectar()) {

        if (con == null) {
            mostrarError("No se pudo conectar a la base de datos. El pasajero no se guardó.");
            return;
        }

        PreparedStatement psDoc = con.prepareStatement(
            "INSERT INTO documento (nro_doc, tipo_doc, fecha_emision, fecha_vencimiento, tipo_residencia, edad) "
            + "VALUES (?, ?, ?, ?, ?, ?)"
        );
        psDoc.setString(1, doc.getNro_doc());
        psDoc.setString(2, doc.getTipo_doc());
        psDoc.setDate(3, java.sql.Date.valueOf(doc.getFecha_emision()));
        psDoc.setDate(4, java.sql.Date.valueOf(doc.getFecha_vencimiento()));
        psDoc.setString(5, doc.getTipo_residencia());
        psDoc.setInt(6, doc.getEdad());
        psDoc.executeUpdate();

        PreparedStatement psPas = con.prepareStatement(
            "INSERT INTO pasajero (nro_doc, ap_paterno, ap_materno, nombre, telefono, correo) "
            + "VALUES (?, ?, ?, ?, ?, ?)"
        );
        psPas.setString(1, doc.getNro_doc());
        psPas.setString(2, pasajero.getAp_paterno());
        psPas.setString(3, pasajero.getAp_materno());
        psPas.setString(4, pasajero.getNombre());
        psPas.setString(5, pasajero.getTelefono());
        psPas.setString(6, pasajero.getCorreo());
        psPas.executeUpdate();

    } catch (Exception ex) {
        mostrarError("El pasajero se registró en el sistema, pero hubo un error al guardarlo en la base de datos:\n" + ex.getMessage());
        return;
    }

    JOptionPane.showMessageDialog(this,
            "Pasajero " + pasajero.unificarDatos() + " registrado correctamente"
            + "Ahora puede asignarlo a un paquete turístico");     
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAsignarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarPaqueteActionPerformed
        // TODO add your handling code here:
            String nroDoc = txtNumDoc.getText().trim();

    if (nroDoc.isEmpty()) {
        mostrarError("Ingrese el N° de documento del pasajero a asignar");
        txtNumDoc.requestFocus();
        return;
    }

    Pasajero pasajero = pc.buscarDocumento(nroDoc);

    if (pasajero == null) {
        mostrarError("Primero debe registrar al pasajero");
        return;
    }

    PaqueteTuristico paquete = (PaqueteTuristico) cbxPaquete.getSelectedItem();

    if (paquete == null) {
        mostrarError("Seleccione un paquete turístico");
        return;
    }

    if (rc.buscarReservaActiva(nroDoc, paquete.getCodigo_paquete()) != null) {
        mostrarError("El pasajero ya está registrado en el paquete " + paquete.getNombre_paquete() +
                "Reinscripción no permitida");
        return;
    }

    if (!paquete.tieneCupos()) {
        mostrarError("No hay cupos disponibles en el paquete " + paquete.getNombre_paquete() + "Sin cupos disponibles");
        return;
    }

    boolean asignado = rc.registrarReserva(pasajero, paquete, 0);

    if (asignado) {

        try (Connection con = ConexionBD.conectar()) {

            if (con == null) {
                mostrarError("No se pudo conectar a la base de datos. La reserva no se guardó.");
                return;
            }

            String codigoReserva = "RES-" + System.currentTimeMillis();

            PreparedStatement psReserva = con.prepareStatement(
                "INSERT INTO Reserva (codigo_reserva, nro_doc, codigo_paquete, precio_final, estado, estado_aprobacion, fecha_reserva) "
                + "VALUES (?, ?, ?, ?, 'Activa', 'Pendiente', ?)"
            );
            psReserva.setString(1, codigoReserva);
            psReserva.setString(2, nroDoc);
            psReserva.setString(3, paquete.getCodigo_paquete());
            psReserva.setDouble(4, paquete.getCosto());
            psReserva.setDate(5, java.sql.Date.valueOf(LocalDate.now()));
            psReserva.executeUpdate();

            PreparedStatement psCupo = con.prepareStatement(
                "UPDATE PaqueteTuristico SET cupos_disponibles = cupos_disponibles - 1 WHERE codigo_paquete = ?"
            );
            psCupo.setString(1, paquete.getCodigo_paquete());
            psCupo.executeUpdate();

        } catch (Exception ex) {
            mostrarError("La solicitud se registró en el sistema, pero hubo un error al guardarla en la base de datos:\n" + ex.getMessage());
            return;
        }

        JOptionPane.showMessageDialog(this,
                "Solicitud registrada para " + pasajero.unificarDatos() + " en el paquete "
                + paquete.getNombre_paquete() + ". Queda pendiente de aprobación por el asesor de ventas.");

        cargarPaquetes();
        actualizarInfoCupos();
        cbxPaquete.repaint();
    } else {
        mostrarError("No se pudo asignar el paquete. Verifique que el documento del pasajero esté vigente.");
    }
    }//GEN-LAST:event_btnAsignarPaqueteActionPerformed

    private void cbxPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaqueteActionPerformed
        // TODO add your handling code here:
        actualizarInfoCupos();
    }//GEN-LAST:event_cbxPaqueteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarPaquete;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnValidarDocumento;
    private javax.swing.JComboBox<PaqueteTuristico> cbxPaquete;
    private javax.swing.JComboBox<String> cbxResidencia;
    private javax.swing.JComboBox<String> cbxTipoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCupos;
    private javax.swing.JLabel lblVigencia;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFechaEmision;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
