/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesGuiaTuristico;

import cristorey_ef.PaqueteTuristico;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Usuario
 */
public class PnlTour extends javax.swing.JPanel {

    /**
     * Creates new form pnlTour
     */
    public PnlTour() {
        initComponents();
    }

    public void cargarDatos(PaqueteTuristico paquete, ActionListener accion) {

        lblNombre.setText(
                paquete.getCodigo_paquete()
                + " - "
                + paquete.getNombre_paquete());

        lblHorario.setText("Horario: " + paquete.getHorario());

        btnPedirAsignacion.addActionListener(accion);
    }
    
    public JButton getBotonAsignacion() {
        return btnPedirAsignacion;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        btnPedirAsignacion = new javax.swing.JButton();

        setBackground(new java.awt.Color(253, 251, 248));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 189, 105), 2));

        lblNombre.setText("Cod - Nombre Tour");

        lblHorario.setText("Horario");

        btnPedirAsignacion.setBackground(new java.awt.Color(255, 189, 105));
        btnPedirAsignacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPedirAsignacion.setForeground(new java.awt.Color(255, 255, 255));
        btnPedirAsignacion.setText("Pedir asignación");
        btnPedirAsignacion.setBorderPainted(false);
        btnPedirAsignacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHorario)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                .addComponent(btnPedirAsignacion)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addComponent(lblHorario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnPedirAsignacion)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedirAsignacion;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
