/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesGuiaTuristico;

import cristorey_ef.GuiaTuristico;
import cristorey_ef.PaqueteTuristico;
import cristorey_ef.PaqueteTuristicoControlador;
import cristorey_ef.UsuarioControlador;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class SolicitarRecorrido extends javax.swing.JPanel {

    private UsuarioControlador uc;
    private final PaqueteTuristicoControlador ptc;
    private final ArrayList<JButton> botonesSolicitud = new ArrayList<>();
    private GuiaTuristico guia;

    public SolicitarRecorrido(UsuarioControlador uc, PaqueteTuristicoControlador ptc) {
        initComponents();
        this.uc = uc;
        this.ptc = ptc;
        construirLista();
        actualizarEstado();
    }
    
    public void setGuiaActual(GuiaTuristico guia) {
        this.guia = guia;
        actualizarEstado();
    }

    public void actualizarEstado() {
        if (guia == null) {
            return;
        }
        if (guia.tieneAsignacion()) {
            lblEstado.setText("Ya tienes un recorrido asignado: " + guia.getRecorrido_asignado()
                    + ". No puedes pedir otro.");
            lblEstado.setForeground(new Color(127, 16, 16));
            bloquearBotones(true);
        } else if (guia.tieneSolicitudPendiente()) {
            lblEstado.setText("Tienes una solicitud pendiente para \"" + guia.getRecorrido_solicitado()
                    + "\". Espera la validación del asesor de ventas.");
            lblEstado.setForeground(new Color(196, 130, 40));
            bloquearBotones(true);
        } else {
            lblEstado.setText("Elige el recorrido al que deseas ser asignado.");
            lblEstado.setForeground(new Color(102, 102, 102));
            bloquearBotones(false);
        }
    }

    private void bloquearBotones(boolean bloquear) {
        for (JButton boton : botonesSolicitud) {
            boton.setEnabled(!bloquear);
        }
    }

    private void pedirAsignacion(PaqueteTuristico paquete) {
        boolean enviada = guia.solicitarAsignacion(paquete.getCodigo_paquete());

        if (enviada) {
            JOptionPane.showMessageDialog(this,
                    "Solicitud enviada para \"" + paquete.getNombre_paquete() + "\".\n"
                    + "El asesor de ventas fue notificado y validará tu pedido.");
            actualizarEstado();
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo enviar la solicitud. Es posible que ya tengas un recorrido "
                    + "asignado o una solicitud pendiente.",
                    "Solicitud no permitida", JOptionPane.WARNING_MESSAGE);
            actualizarEstado();
        }
    }
    
    
    private void construirLista() {

        pnlLista.removeAll();
        botonesSolicitud.clear();

        for (PaqueteTuristico paquete : ptc.getPaquete()) {

            PnlTour panel = new PnlTour();

            panel.cargarDatos(
                    paquete,
                    e -> pedirAsignacion(paquete));
            botonesSolicitud.add(panel.getBotonAsignacion());
            pnlLista.add(panel);
        }

        pnlLista.revalidate();
        pnlLista.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jScrollPaneLista = new javax.swing.JScrollPane();
        pnlLista = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 249, 236));
        setLayout(new java.awt.GridBagLayout());

        jLabel.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel.setForeground(new java.awt.Color(80, 50, 22));
        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/solicitarRecorrido.png"))); // NOI18N
        jLabel.setText("Solicitar recorrido turistico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        add(jLabel, gridBagConstraints);

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(102, 102, 102));
        lblEstado.setText("Elige el recorrido al que deseas ser asignado.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 29, 0, 0);
        add(lblEstado, gridBagConstraints);

        jScrollPaneLista.setBorder(null);
        jScrollPaneLista.setPreferredSize(new java.awt.Dimension(560, 320));

        pnlLista.setBackground(new java.awt.Color(255, 255, 255));
        pnlLista.setLayout(new javax.swing.BoxLayout(pnlLista, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneLista.setViewportView(pnlLista);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 691;
        gridBagConstraints.ipady = 334;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 26, 31, 21);
        add(jScrollPaneLista, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel;
    private javax.swing.JScrollPane jScrollPaneLista;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JPanel pnlLista;
    // End of variables declaration//GEN-END:variables
}
