/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesGuiaTuristico;

import cristorey_ef.GuiaTuristico;
import cristorey_ef.PaqueteTuristicoControlador;
import cristorey_ef.PasajeroControlador;
import cristorey_ef.ReservaControlador;
import cristorey_ef.UsuarioControlador;
import cristorey_ef.VentanaPrincipal;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipalGuia extends javax.swing.JPanel {

    /**
     * Creates new form PantallaAdministrador
     */
    Inicio i;
    RecorridoTuristico rt;
    SolicitarRecorrido sr;
    
    private JPanel panelSeleccionado;
    private boolean expandido = false;
    public VentanaPrincipalGuia(UsuarioControlador uc, PasajeroControlador pc,
            ReservaControlador rc, PaqueteTuristicoControlador ptc) {
        initComponents();
        i = new Inicio(rc, ptc, uc);
        rt = new RecorridoTuristico(uc,ptc, rc);
        sr = new SolicitarRecorrido(uc,ptc);
        pnlMenu.setPreferredSize(new Dimension(50, pnlMenu.getHeight()));
        pnlMenu.revalidate();
        JPanel[] paneles = {i,rt,sr};

        for(int j = 0; j < paneles.length; j++){
            JPanel panel = paneles[j];
            lypPrincipal.add(panel);
        }

        mostrarPanel(i);
        seleccionarMenu(pnlInicio);
    }
    
    public void seleccionarMenu(JPanel panel) {

        panelSeleccionado = panel;
        JPanel[] paneles = {
            pnlInicio,
            pnlTourAsignado,
            pnlSolicitarTour
        };

        for(int j = 0; j < paneles.length; j++){
            paneles[j].setBackground(Color.WHITE);
        }

        if (expandido && panelSeleccionado != null) {
        panelSeleccionado.setBackground(new Color(255,170,44));
        }
    }
    void mostrarPanel(JPanel panelVisible){

        JPanel[] paneles = {i, rt, sr};

        for(int j = 0; j < paneles.length; j++){
            JPanel panel = paneles[j];
            panel.setVisible(false);
        }

        panelVisible.setVisible(true);
    }
    GuiaTuristico guiaActual;
    public void setUsuarioActual(GuiaTuristico guia) {
        this.guiaActual = guia;
        sr.setGuiaActual(guia);
        rt.setGuiaActual(guia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        pnlInicio = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        pnlCerrarSesion = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        pnlTourAsignado = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnTourAsignado = new javax.swing.JButton();
        pnlSolicitarTour = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnSolicitarTour = new javax.swing.JButton();
        lypPrincipal = new javax.swing.JLayeredPane();

        setLayout(new java.awt.BorderLayout());

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono1.png"))); // NOI18N

        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(64, 48, 0));
        btnMenu.setText("...");
        btnMenu.setAutoscrolls(true);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setFocusPainted(false);
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        pnlInicio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/inicio.png"))); // NOI18N

        btnInicio.setText("Inicio    ");
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(btnInicio))
                .addContainerGap())
        );

        pnlCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir.png"))); // NOI18N

        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        javax.swing.GroupLayout pnlCerrarSesionLayout = new javax.swing.GroupLayout(pnlCerrarSesion);
        pnlCerrarSesion.setLayout(pnlCerrarSesionLayout);
        pnlCerrarSesionLayout.setHorizontalGroup(
            pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCerrarSesionLayout.setVerticalGroup(
            pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerrarSesionLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(btnCerrarSesion))
                .addGap(9, 9, 9))
        );

        pnlTourAsignado.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mapa.png"))); // NOI18N

        btnTourAsignado.setText("Tour asignado");
        btnTourAsignado.setBorderPainted(false);
        btnTourAsignado.setContentAreaFilled(false);
        btnTourAsignado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTourAsignado.setFocusPainted(false);
        btnTourAsignado.addActionListener(this::btnTourAsignadoActionPerformed);

        javax.swing.GroupLayout pnlTourAsignadoLayout = new javax.swing.GroupLayout(pnlTourAsignado);
        pnlTourAsignado.setLayout(pnlTourAsignadoLayout);
        pnlTourAsignadoLayout.setHorizontalGroup(
            pnlTourAsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTourAsignadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTourAsignado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTourAsignadoLayout.setVerticalGroup(
            pnlTourAsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTourAsignadoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlTourAsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTourAsignado)
                    .addComponent(jLabel17))
                .addGap(8, 8, 8))
        );

        pnlSolicitarTour.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/elegir.png"))); // NOI18N

        btnSolicitarTour.setText("Solicitar Tour");
        btnSolicitarTour.setBorderPainted(false);
        btnSolicitarTour.setContentAreaFilled(false);
        btnSolicitarTour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSolicitarTour.setFocusPainted(false);
        btnSolicitarTour.addActionListener(this::btnSolicitarTourActionPerformed);

        javax.swing.GroupLayout pnlSolicitarTourLayout = new javax.swing.GroupLayout(pnlSolicitarTour);
        pnlSolicitarTour.setLayout(pnlSolicitarTourLayout);
        pnlSolicitarTourLayout.setHorizontalGroup(
            pnlSolicitarTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitarTourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSolicitarTour)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSolicitarTourLayout.setVerticalGroup(
            pnlSolicitarTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitarTourLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlSolicitarTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSolicitarTour)
                    .addComponent(jLabel18))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTourAsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSolicitarTour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(pnlCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTourAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSolicitarTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(pnlCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        add(pnlMenu, java.awt.BorderLayout.LINE_START);

        lypPrincipal.setLayout(new java.awt.CardLayout());
        add(lypPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        expandido = !expandido;

        if (expandido) {
            pnlMenu.setPreferredSize(new Dimension(220, pnlMenu.getHeight()));
        } else {
            pnlMenu.setPreferredSize(new Dimension(50, pnlMenu.getHeight()));
        }

        seleccionarMenu(panelSeleccionado);

        pnlMenu.revalidate();
        pnlMenu.repaint();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlInicio);
        mostrarPanel(i);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnTourAsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTourAsignadoActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlTourAsignado);
        rt.setGuiaActual(guiaActual);
        mostrarPanel(rt);
    }//GEN-LAST:event_btnTourAsignadoActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventana =(VentanaPrincipal) SwingUtilities.getWindowAncestor(this);
        ventana.volverInicio();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnSolicitarTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarTourActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlSolicitarTour);
        sr.actualizarEstado();
        mostrarPanel(sr);
    }//GEN-LAST:event_btnSolicitarTourActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSolicitarTour;
    private javax.swing.JButton btnTourAsignado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLayeredPane lypPrincipal;
    private javax.swing.JPanel pnlCerrarSesion;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlSolicitarTour;
    private javax.swing.JPanel pnlTourAsignado;
    // End of variables declaration//GEN-END:variables
}
