/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesGenerales;
import Conexion.ConexionBD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

import cristorey_ef.PaqueteTuristico;
import cristorey_ef.PaqueteTuristicoControlador;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ControlViajes extends javax.swing.JPanel {

    /**
     * Creates new form Tours
     */
    private PaqueteTuristicoControlador ptc;
    
    public ControlViajes(PaqueteTuristicoControlador ptc) {
    initComponents();
    this.ptc = ptc;

    tblPaquetes.getTableHeader().setBackground(new java.awt.Color(255, 170, 44));
    tblPaquetes.getTableHeader().setForeground(java.awt.Color.WHITE);
    tblPaquetes.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer(){
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            javax.swing.JLabel c = (javax.swing.JLabel) super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);
            c.setBackground(table.getTableHeader().getBackground());
            c.setForeground(table.getTableHeader().getForeground());
            c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            c.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, java.awt.Color.LIGHT_GRAY));

            return c;
        }
    });
    cargarTabla();
}
   
    
    private void cargarTabla() {
        
        DefaultTableModel modelo = (DefaultTableModel) tblPaquetes.getModel();
        modelo.setRowCount(0);

    try (Connection con = ConexionBD.conectar()) {

        if (con == null) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo conectar a la base de datos.",
                    "Error de conexión", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(
            "SELECT nombre_paquete, horario, cupos_maximos, cupos_disponibles, costo "
            + "FROM PaqueteTuristico"
        );

        while (rs.next()) {
            String nombre = rs.getString("nombre_paquete");
            String horario = rs.getString("horario");
            int cuposMax = rs.getInt("cupos_maximos");
            int cuposDisp = rs.getInt("cupos_disponibles");
            double costo = rs.getDouble("costo");

            int inscritos = cuposMax - cuposDisp;
            double porcentaje = cuposMax > 0 ? (inscritos * 100.0 / cuposMax) : 0;

            modelo.addRow(new Object[]{
                nombre,
                horario,
                inscritos,
                cuposMax,
                cuposDisp,
                String.format("%.1f %%", porcentaje),
                costo
            });
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Error al cargar los paquetes desde la base de datos:\n" + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
}
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPaquetes = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 249, 236));

        jLabel17.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(80, 50, 22));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ControlViajes.png"))); // NOI18N
        jLabel17.setText("Control de viajes diarios");

        tblPaquetes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Paquete Turístico", "Horario", "Inscritos", "Cupos Máx.", "Disponibles", "%  Ocupado", "Precio"
            }
        ));
        tblPaquetes.setMaximumSize(new java.awt.Dimension(30, 350));
        tblPaquetes.setMinimumSize(new java.awt.Dimension(30, 350));
        tblPaquetes.setPreferredSize(new java.awt.Dimension(30, 350));
        tblPaquetes.setRowHeight(28);
        tblPaquetes.setShowHorizontalLines(true);
        tblPaquetes.setShowVerticalLines(true);
        jScrollPane2.setViewportView(tblPaquetes);

        btnActualizar.setBackground(new java.awt.Color(255, 189, 105));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorderPainted(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/paisaje 7.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 254, 22, 257);
        jPanel1.add(jLabel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cargarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPaquetes;
    // End of variables declaration//GEN-END:variables
}
