/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesAdministrador;

import cristorey_ef.PaqueteTuristico;
import cristorey_ef.ReservaControlador;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Estadisticas extends javax.swing.JPanel {

    /**
     * Creates new form Estadisticas
     */
    private ReservaControlador rc;

    public Estadisticas(ReservaControlador rc) {
        initComponents();

        this.rc=rc;
        tblRanking.getTableHeader().setBackground(new java.awt.Color(255, 170, 44));
        tblRanking.getTableHeader().setForeground(java.awt.Color.WHITE);
        tblRanking.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer(){
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                javax.swing.JLabel c = (javax.swing.JLabel) super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);
                c.setBackground(table.getTableHeader().getBackground());
                c.setForeground(table.getTableHeader().getForeground());
                c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                c.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, java.awt.Color.LIGHT_GRAY));

                return c;
            }
        });

        lblMes.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("EEEE, dd 'de' MMMM 'de' yyyy")));

        cargarEstadisticas();
    }

    private void cargarEstadisticas() {
        double ganancias = rc.gananciasUltimoMes();
        lblGanancias.setText(String.valueOf("S/"+ ganancias));

        String diaPopular = rc.diaMasConcurridoUltimoMes();
        lblDiaConcurrido.setText(diaPopular);

        DefaultTableModel modelo = (DefaultTableModel) tblRanking.getModel();
        modelo.setRowCount(0);

        ArrayList<ReservaControlador.RankingPaquete> ranking = rc.rankingPopularidadPaquetes();

        if (ranking.isEmpty()) {
            modelo.addRow(new Object[]{"Sin reservas registradas este mes", "-", "-", "-"});
            return;
        }

        for (int i = 0; i < ranking.size(); i++) {
            ReservaControlador.RankingPaquete item = ranking.get(i);
            PaqueteTuristico p = item.getPaquete();
            modelo.addRow(new Object[]{
                p.getNombre_paquete(),
                p.getDestino(),
                item.getCantidadReservas(),
                String.format("%.1f %%", item.getPorcentaje())
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblGanancias = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblDiaConcurrido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRanking = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 249, 236));

        jLabel17.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(80, 50, 22));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Estadisticas.png"))); // NOI18N
        jLabel17.setText("Estadísticas");

        lblMes.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblMes.setText("Fecha actual");

        jButton1.setBackground(new java.awt.Color(255, 189, 105));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Generar Reporte");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 164, 61), 2));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ganancias del mes");
        jPanel1.add(jLabel1);

        lblGanancias.setFont(new java.awt.Font("Forte", 0, 26)); // NOI18N
        lblGanancias.setForeground(new java.awt.Color(245, 164, 61));
        lblGanancias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGanancias.setText("S/ 0.00");
        jPanel1.add(lblGanancias);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 164, 61), 2));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Día más concurrido");
        jPanel2.add(jLabel3);

        lblDiaConcurrido.setFont(new java.awt.Font("Forte", 0, 26)); // NOI18N
        lblDiaConcurrido.setForeground(new java.awt.Color(245, 164, 61));
        lblDiaConcurrido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiaConcurrido.setText("-");
        jPanel2.add(lblDiaConcurrido);

        tblRanking.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Paquete", "Destino", "Reservas", "% Popularidad"
            }
        ));
        tblRanking.setRowHeight(28);
        tblRanking.setShowHorizontalLines(true);
        tblRanking.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblRanking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(186, 186, 186)
                        .addComponent(lblMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMes)
                            .addComponent(jButton1))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargarEstadisticas();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiaConcurrido;
    private javax.swing.JLabel lblGanancias;
    private javax.swing.JLabel lblMes;
    private javax.swing.JTable tblRanking;
    // End of variables declaration//GEN-END:variables
}
