/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesAdministrador;

import cristorey_ef.VentanaPrincipal;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipalAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PantallaAdministrador
     */
    Inicio i = new Inicio();
    Pasajeros p = new Pasajeros();
    Tours t = new Tours();
    Estadisticas e = new Estadisticas();
    ControlMatutino c = new ControlMatutino();
    GestionarAccesos g = new GestionarAccesos();
    private JPanel panelSeleccionado;
    private boolean expandido = false;
    public VentanaPrincipalAdmin() {
        initComponents();
        pnlMenu.setPreferredSize(new Dimension(50, pnlMenu.getHeight()));
        pnlMenu.revalidate();
        JPanel[] paneles = {i,p,t,e,c,g};

        for(JPanel panel : paneles){
            lypPrincipal.add(panel);
        }

        mostrarPanel(i);
        seleccionarMenu(pnlInicio);
    }
    
    private void seleccionarMenu(JPanel panel) {

        panelSeleccionado = panel;
        JPanel[] paneles = {
            pnlInicio,
            pnlPasajeros,
            pnlTours,
            pnlEstadisticas,
            pnlControlMatutino,
            pnlGestionarAccesos
        };

        for (JPanel p : paneles) {
            p.setBackground(Color.WHITE);
        }

        if (expandido && panelSeleccionado != null) {
        panelSeleccionado.setBackground(new Color(255,170,44));
        }
    }
    private void mostrarPanel(JPanel panelVisible){

        JPanel[] paneles = {i, p, t, e, c, g};

        for(JPanel panel : paneles){
            panel.setVisible(false);
        }

        panelVisible.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        pnlInicio = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        pnlPasajeros = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnPasajeros = new javax.swing.JButton();
        pnlEstadisticas = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnEstadisticas = new javax.swing.JButton();
        pnlControlMatutino = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnControlMatutino = new javax.swing.JButton();
        pnlGestionarAccesos = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnGestionarAccesos = new javax.swing.JButton();
        pnlCerrarSesion = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        pnlTours = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnTours = new javax.swing.JButton();
        lypPrincipal = new javax.swing.JLayeredPane();

        setLayout(new java.awt.BorderLayout());

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono1.png"))); // NOI18N

        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(64, 48, 0));
        btnMenu.setText("...");
        btnMenu.setAutoscrolls(true);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setFocusPainted(false);
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        pnlInicio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/inicio.png"))); // NOI18N

        btnInicio.setText("Inicio    ");
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(btnInicio))
                .addContainerGap())
        );

        pnlPasajeros.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/clientes.png"))); // NOI18N

        btnPasajeros.setText(" Pasajeros");
        btnPasajeros.setBorderPainted(false);
        btnPasajeros.setContentAreaFilled(false);
        btnPasajeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPasajeros.setFocusPainted(false);
        btnPasajeros.addActionListener(this::btnPasajerosActionPerformed);

        javax.swing.GroupLayout pnlPasajerosLayout = new javax.swing.GroupLayout(pnlPasajeros);
        pnlPasajeros.setLayout(pnlPasajerosLayout);
        pnlPasajerosLayout.setHorizontalGroup(
            pnlPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasajerosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPasajeros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPasajerosLayout.setVerticalGroup(
            pnlPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasajerosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(btnPasajeros))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEstadisticas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/histograma-de-grafico.png"))); // NOI18N

        btnEstadisticas.setText("Estadisticas");
        btnEstadisticas.setBorderPainted(false);
        btnEstadisticas.setContentAreaFilled(false);
        btnEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstadisticas.setFocusPainted(false);
        btnEstadisticas.addActionListener(this::btnEstadisticasActionPerformed);

        javax.swing.GroupLayout pnlEstadisticasLayout = new javax.swing.GroupLayout(pnlEstadisticas);
        pnlEstadisticas.setLayout(pnlEstadisticasLayout);
        pnlEstadisticasLayout.setHorizontalGroup(
            pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEstadisticasLayout.setVerticalGroup(
            pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                .addGroup(pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel16))
                    .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnEstadisticas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlControlMatutino.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/calendario.png"))); // NOI18N

        btnControlMatutino.setText("Control matutino");
        btnControlMatutino.setBorderPainted(false);
        btnControlMatutino.setContentAreaFilled(false);
        btnControlMatutino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnControlMatutino.setFocusPainted(false);
        btnControlMatutino.addActionListener(this::btnControlMatutinoActionPerformed);

        javax.swing.GroupLayout pnlControlMatutinoLayout = new javax.swing.GroupLayout(pnlControlMatutino);
        pnlControlMatutino.setLayout(pnlControlMatutinoLayout);
        pnlControlMatutinoLayout.setHorizontalGroup(
            pnlControlMatutinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlMatutinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnControlMatutino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlControlMatutinoLayout.setVerticalGroup(
            pnlControlMatutinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlMatutinoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlControlMatutinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnControlMatutino)
                    .addComponent(jLabel14))
                .addGap(8, 8, 8))
        );

        pnlGestionarAccesos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/control-de-acceso.png"))); // NOI18N

        btnGestionarAccesos.setText("Gestionar accesos");
        btnGestionarAccesos.setBorderPainted(false);
        btnGestionarAccesos.setContentAreaFilled(false);
        btnGestionarAccesos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionarAccesos.setFocusPainted(false);
        btnGestionarAccesos.addActionListener(this::btnGestionarAccesosActionPerformed);

        javax.swing.GroupLayout pnlGestionarAccesosLayout = new javax.swing.GroupLayout(pnlGestionarAccesos);
        pnlGestionarAccesos.setLayout(pnlGestionarAccesosLayout);
        pnlGestionarAccesosLayout.setHorizontalGroup(
            pnlGestionarAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestionarAccesosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionarAccesos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGestionarAccesosLayout.setVerticalGroup(
            pnlGestionarAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestionarAccesosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlGestionarAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(btnGestionarAccesos))
                .addGap(8, 8, 8))
        );

        pnlCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir.png"))); // NOI18N

        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        javax.swing.GroupLayout pnlCerrarSesionLayout = new javax.swing.GroupLayout(pnlCerrarSesion);
        pnlCerrarSesion.setLayout(pnlCerrarSesionLayout);
        pnlCerrarSesionLayout.setHorizontalGroup(
            pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCerrarSesionLayout.setVerticalGroup(
            pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerrarSesionLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(btnCerrarSesion))
                .addGap(9, 9, 9))
        );

        pnlTours.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/viaje-en-coche.png"))); // NOI18N

        btnTours.setText("Tours     ");
        btnTours.setBorderPainted(false);
        btnTours.setContentAreaFilled(false);
        btnTours.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTours.setFocusPainted(false);
        btnTours.addActionListener(this::btnToursActionPerformed);

        javax.swing.GroupLayout pnlToursLayout = new javax.swing.GroupLayout(pnlTours);
        pnlTours.setLayout(pnlToursLayout);
        pnlToursLayout.setHorizontalGroup(
            pnlToursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToursLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTours)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlToursLayout.setVerticalGroup(
            pnlToursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToursLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlToursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTours)
                    .addComponent(jLabel17))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlControlMatutino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlGestionarAccesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControlMatutino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGestionarAccesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(pnlCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        add(pnlMenu, java.awt.BorderLayout.LINE_START);

        lypPrincipal.setLayout(new java.awt.CardLayout());
        add(lypPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        expandido = !expandido;

        if (expandido) {
            pnlMenu.setPreferredSize(new Dimension(220, pnlMenu.getHeight()));
        } else {
            pnlMenu.setPreferredSize(new Dimension(50, pnlMenu.getHeight()));
        }

        seleccionarMenu(panelSeleccionado);

        pnlMenu.revalidate();
        pnlMenu.repaint();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlInicio);
        mostrarPanel(i);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasajerosActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlPasajeros);
        mostrarPanel(p);
    }//GEN-LAST:event_btnPasajerosActionPerformed

    private void btnToursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToursActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlTours);
        mostrarPanel(t);
    }//GEN-LAST:event_btnToursActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlEstadisticas);
        mostrarPanel(e);
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnControlMatutinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlMatutinoActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlControlMatutino);
        mostrarPanel(c);
    }//GEN-LAST:event_btnControlMatutinoActionPerformed

    private void btnGestionarAccesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarAccesosActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlGestionarAccesos);
        mostrarPanel(g);
    }//GEN-LAST:event_btnGestionarAccesosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventana =(VentanaPrincipal) SwingUtilities.getWindowAncestor(this);
        ventana.volverInicio();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnControlMatutino;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnGestionarAccesos;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPasajeros;
    private javax.swing.JButton btnTours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLayeredPane lypPrincipal;
    private javax.swing.JPanel pnlCerrarSesion;
    private javax.swing.JPanel pnlControlMatutino;
    private javax.swing.JPanel pnlEstadisticas;
    private javax.swing.JPanel pnlGestionarAccesos;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPasajeros;
    private javax.swing.JPanel pnlTours;
    // End of variables declaration//GEN-END:variables
}
