/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesGerente;

import cristorey_ef.ReservaControlador;
import javax.swing.JOptionPane;

/** 
 *
 * @author coolg
 */
public class MargenUtilidad extends javax.swing.JPanel {

    private final ReservaControlador rc;

    /**
     * Creates new form MargenUtilidad
     */
    public MargenUtilidad(ReservaControlador rc) {
        this.rc = rc;
        initComponents();
        estilizarComponentes();
    }

    private void estilizarComponentes() {
        panelPastel.setBackground(java.awt.Color.WHITE);
        panelPastel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 164, 61), 2));

        lblResultado.setOpaque(true);
        lblResultado.setBackground(java.awt.Color.WHITE);
        lblResultado.setFont(new java.awt.Font("Segoe UI", 0, 13));
        lblResultado.setForeground(new java.awt.Color(80, 50, 22));
        lblResultado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        aplicarBordeResultado(false);

        mostrarResultadoVacio();
    }

    private void aplicarBordeResultado(boolean enPerdida) {
        java.awt.Color colorBorde;
        if (enPerdida) {
            colorBorde = new java.awt.Color(127, 16, 16);  
        } else {
            colorBorde = new java.awt.Color(245, 164, 61);
        }
        lblResultado.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(colorBorde, 2),
                javax.swing.BorderFactory.createEmptyBorder(14, 16, 14, 16)));
    }

    private void mostrarResultadoVacio() {
        lblResultado.setText("<html>Ingresa los costos del mes y presiona<br>"
                + "\u201CCalcular margen neto\u201D para ver el balance.</html>");
    }
    
    public void refrescar() {
        calcular();
    }

    private void calcular() {
        double pagoGuias;
        double transporte;
        double entradas;
        try {
            pagoGuias = Double.parseDouble(txtPagoGuias.getText().trim());
            transporte = Double.parseDouble(txtTransporte.getText().trim());
            entradas = Double.parseDouble(txtEntradas.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos en los tres campos.",
                    "Dato inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (pagoGuias < 0 || transporte < 0 || entradas < 0) {
            JOptionPane.showMessageDialog(this, "Los costos no pueden ser negativos.",
                    "Dato inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double ingresos = rc.gananciasUltimoMes();
        double costos = pagoGuias + transporte + entradas;
        double margenNeto = ingresos - costos;
        double porcentajeGanancia;
        if (ingresos == 0) {
            porcentajeGanancia = 0; 
        } else {
            porcentajeGanancia = (margenNeto / ingresos) * 100; 
        }
        boolean enPerdida = margenNeto < 0;

        aplicarBordeResultado(enPerdida);

       String colorMargen;

        if (enPerdida) {
            colorMargen = "#7F1010";
        } else {
            colorMargen = "#C87A22"; 
        }

        lblResultado.setText("<html>"
                + "Ingresos brutos: S/" + String.format("%.2f", ingresos)
                + "<br>Costos operativos: S/" + String.format("%.2f", costos)
                + "<br><font color='" + colorMargen + "' size='+1'><b>Margen neto: S/"
                + String.format("%.2f", margenNeto) + "</b></font>"
                + "<br>Ganancia neta: " + String.format("%.1f", porcentajeGanancia) + "%"
                + (enPerdida ? "<br><i>El mes cerraría en pérdida.</i>" : "")
                + "</html>");

        panelPastel.actualizar(Math.max(margenNeto, 0), costos);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblPagoGuias = new javax.swing.JLabel();
        txtPagoGuias = new javax.swing.JTextField();
        lblTransporte = new javax.swing.JLabel();
        txtTransporte = new javax.swing.JTextField();
        lblEntradas = new javax.swing.JLabel();
        txtEntradas = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        panelPastel = new PanelesGerente.PanelPastel();

        setBackground(new java.awt.Color(252, 242, 226));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblTitulo.setFont(new java.awt.Font("Forte", 0, 22)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(80, 50, 22));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/margenUtilidad.png"))); // NOI18N
        lblTitulo.setText("Margen de utilidad (mes actual)");

        lblPagoGuias.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblPagoGuias.setForeground(new java.awt.Color(80, 50, 22));
        lblPagoGuias.setText("Pago a guías (S/):");

        txtPagoGuias.setText("0");

        lblTransporte.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTransporte.setForeground(new java.awt.Color(80, 50, 22));
        lblTransporte.setText("Transporte (S/):");

        txtTransporte.setText("0");

        lblEntradas.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblEntradas.setForeground(new java.awt.Color(80, 50, 22));
        lblEntradas.setText("Entradas a atracciones (S/):");

        txtEntradas.setText("0");

        btnCalcular.setBackground(new java.awt.Color(255, 189, 105));
        btnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular margen neto");
        btnCalcular.setBorderPainted(false);
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPagoGuias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPagoGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTransporte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEntradas)
                                .addGap(29, 29, 29)
                                .addComponent(txtEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnCalcular)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPagoGuias)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtPagoGuias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTransporte)
                            .addComponent(txtTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEntradas)
                            .addComponent(txtEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcular))
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(panelPastel, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {
        calcular();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblEntradas;
    private javax.swing.JLabel lblPagoGuias;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTransporte;
    private PanelesGerente.PanelPastel panelPastel;
    private javax.swing.JTextField txtEntradas;
    private javax.swing.JTextField txtPagoGuias;
    private javax.swing.JTextField txtTransporte;
    // End of variables declaration//GEN-END:variables

}
