/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesGerente;

import cristorey_ef.Gerente;
import cristorey_ef.ReservaControlador;
import javax.swing.JOptionPane;

/**
 * HU004 #4 - Alertas de metas de ventas: barra de progreso comparando las
 * ventas del mes actual contra la meta configurada por el Gerente.
 *
 * Convertido a JPanel Form: campo, botón y barra de progreso se editan desde
 * Design. La lógica (guardarMeta, refrescar) queda en Source.
 *
 * @author coolg
 */
public class MetasVentas extends javax.swing.JPanel {

    /**
     * Creates new form MetasVentas
     */
    private final ReservaControlador rc;
    private Gerente gerente;
    public MetasVentas(ReservaControlador rc) {
        this.rc = rc;
        initComponents();
    }

    private void guardarMeta() {
        try {
            double meta = Double.parseDouble(txtMeta.getText().trim());
            if (meta <= 0) {
                JOptionPane.showMessageDialog(this, "La meta debe ser un valor mayor a 0.",
                        "Dato inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }
            gerente.setMeta_venta_mensual(meta);
            JOptionPane.showMessageDialog(this, "Meta de ventas actualizada correctamente.");
            refrescar();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido.",
                    "Dato inválido", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void setGerente(Gerente gerente) {
        this.gerente = gerente;
        refrescar();
    }

    public void refrescar() {
        txtMeta.setText("");
        double ganancias = rc.gananciasUltimoMes();
        double meta;
        
        meta = gerente.getMeta_venta_mensual();

        if (meta <= 0) {
            barra.setValue(0);
            barra.setString("Configure una meta para ver el progreso.");
            lblResumen.setText("Ventas del mes: S/" + ganancias);
            return;
        }

        int progreso = (int) Math.min(100, Math.round((ganancias / meta) * 100));
        barra.setValue(progreso);
        barra.setString(progreso + "%");
        if (progreso >= 100) {
            barra.setForeground(new java.awt.Color(27, 94, 32));
        } else {
            barra.setForeground(new java.awt.Color(255, 170, 44));
        }

        lblResumen.setText("Ventas del mes: S/" + ganancias
                + " Meta: S/" +  meta);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblResumen = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblMeta = new javax.swing.JLabel();
        txtMeta = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        barra = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(252, 242, 226));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblResumen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResumen.setForeground(new java.awt.Color(90, 90, 90));

        jLabel17.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(80, 50, 22));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/metasVentas.png"))); // NOI18N
        jLabel17.setText("Metas de venta");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblMeta.setText("Meta mensual (S/):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 197, 0, 0);
        jPanel1.add(lblMeta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 44, 0, 0);
        jPanel1.add(txtMeta, gridBagConstraints);

        btnGuardar.setBackground(new java.awt.Color(255, 189, 105));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar meta");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(54, 33, 0, 218);
        jPanel1.add(btnGuardar, gridBagConstraints);

        barra.setPreferredSize(new java.awt.Dimension(420, 30));
        barra.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 410;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 197, 0, 218);
        jPanel1.add(barra, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/paisaje 8.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 231, 18, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        btnActualizar.setBackground(new java.awt.Color(255, 189, 105));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(25, 25, 25))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(btnActualizar))
                .addGap(54, 54, 54)
                .addComponent(lblResumen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        guardarMeta();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        refrescar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMeta;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JTextField txtMeta;
    // End of variables declaration//GEN-END:variables

}
