/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesGerente;

import cristorey_ef.PaqueteTuristico;
import cristorey_ef.Reserva;
import cristorey_ef.ReservaControlador;
import java.time.YearMonth;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 * HU004 #6 - Reporte de perdidas por cancelaciones: consolida la cantidad
 * de reservas canceladas por paquete durante el mes actual, junto a la
 * perdida estimada en soles.
 *
 * Convertido a JPanel Form: tabla y etiqueta de total se editan desde
 * Design. La lógica de cálculo (refrescar) queda en Source.
 *
 * @author coolg
 */
public class ReporteCancelaciones extends javax.swing.JPanel {

    /**
     * Creates new form ReporteCancelaciones
     */
    
    private final ReservaControlador rc;
    public ReporteCancelaciones(ReservaControlador rc) {
        this.rc = rc;
        initComponents();
        
        tblReporteCancelaciones.getTableHeader().setBackground(new java.awt.Color(255, 170, 44));
        tblReporteCancelaciones.getTableHeader().setForeground(java.awt.Color.WHITE);
        tblReporteCancelaciones.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer(){
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                javax.swing.JLabel c = (javax.swing.JLabel) super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);
                c.setBackground(table.getTableHeader().getBackground());
                c.setForeground(table.getTableHeader().getForeground());
                c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                c.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, java.awt.Color.LIGHT_GRAY));

                return c;
            }
        });
        cargarTabla();
    }
    
     public void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblReporteCancelaciones.getModel();
        modelo.setRowCount(0);
        YearMonth mesActual = YearMonth.now();

        ArrayList<ReporteCancelacion> listaReporte = new ArrayList<>();
        double totalPerdida = 0;

        ArrayList<Reserva> todasLasReservas = rc.getReserva();

        for (int i = 0; i < todasLasReservas.size(); i++) {
            Reserva r = todasLasReservas.get(i);

            if (!r.getEstado().equalsIgnoreCase("Cancelada")) {
                continue;
            }
            if (r.getFecha_cancelacion() == null || !YearMonth.from(r.getFecha_cancelacion()).equals(mesActual)) {
                continue;
            }

            String codigo = r.getPaquete().getCodigo_paquete();
            double precio = r.getPrecio_final();
            totalPerdida += precio;

            ReporteCancelacion lineaEncontrada = null;
            for (int j = 0; j < listaReporte.size(); j++) {
                ReporteCancelacion linea = listaReporte.get(j);
                if (linea.paquete.getCodigo_paquete().equals(codigo)) {
                    lineaEncontrada = linea;
                    break; 
                }
            }

            if (lineaEncontrada == null) {
                lineaEncontrada = new ReporteCancelacion(r.getPaquete());
                listaReporte.add(lineaEncontrada);
            }

            lineaEncontrada.cantidad = lineaEncontrada.cantidad + 1;
            lineaEncontrada.perdida = lineaEncontrada.perdida + precio;
        }

        for (int i = 0; i < listaReporte.size(); i++) {
            ReporteCancelacion linea = listaReporte.get(i);

            modelo.addRow(new Object[]{
                linea.paquete.getNombre_paquete(),
                linea.cantidad,
                String.format("%.2f", linea.perdida)
            });
        }

        lblTotal.setText("Pérdida total estimada este mes: S/" + totalPerdida);
    }
     
    class ReporteCancelacion {
        PaqueteTuristico paquete;
        int cantidad = 0;
        double perdida = 0.0;

        public ReporteCancelacion(PaqueteTuristico paquete) {
            this.paquete = paquete;
        }
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporteCancelaciones = new javax.swing.JTable();
        btnActualizar2 = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 242, 226));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel17.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(80, 50, 22));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/reservasCanceladas.png"))); // NOI18N
        jLabel17.setText("Reporte de cancelaciones");

        tblReporteCancelaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Paquete", "Reservas canceladas (mes actual)", "Pérdida estimada (S/)"
            }
        ));
        tblReporteCancelaciones.setRowHeight(28);
        tblReporteCancelaciones.setShowHorizontalLines(true);
        tblReporteCancelaciones.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblReporteCancelaciones);

        btnActualizar2.setBackground(new java.awt.Color(255, 189, 105));
        btnActualizar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar2.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar2.setText("Actualizar");
        btnActualizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar2ActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(80, 50, 22));
        lblTotal.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addComponent(btnActualizar2)))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(lblTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblTotal)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar2ActionPerformed
        // TODO add your handling code here:
        cargarTabla();
    }//GEN-LAST:event_btnActualizar2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar2;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblReporteCancelaciones;
    // End of variables declaration//GEN-END:variables

}
