/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesGerente;

import cristorey_ef.Gerente;
import cristorey_ef.PaqueteTuristicoControlador;
import cristorey_ef.ReservaControlador;
import cristorey_ef.UsuarioControlador;
import cristorey_ef.VentanaPrincipal;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipalGerente extends javax.swing.JPanel {

    /**
     * Creates new form PantallaAdministrador
     */
    Inicio i;
    Empleados e;
    MetasVentas mv;
    ReporteCancelaciones r;
    ReporteFinanciero rf;
    Tarifas t;
    MargenUtilidad mu;
    private JPanel panelSeleccionado;
    private boolean expandido = false;
    public VentanaPrincipalGerente(UsuarioControlador uc,
            ReservaControlador rc, PaqueteTuristicoControlador ptc) {
        initComponents();
        i = new Inicio(ptc, uc, rc);
        e = new Empleados(uc);
        mv = new MetasVentas(rc);
        r = new ReporteCancelaciones(rc);
        rf = new ReporteFinanciero(rc);
        t = new Tarifas(ptc);
        mu = new MargenUtilidad(rc);
        pnlMenu.setPreferredSize(new Dimension(50, pnlMenu.getHeight()));
        pnlMenu.revalidate();
        JPanel[] paneles = {i,e,mv,r,rf,t,mu};

        for(int j = 0; j < paneles.length; j++){
            JPanel panel = paneles[j];
            lypPrincipal.add(panel);
        }

        mostrarPanel(i);
        seleccionarMenu(pnlInicio);
    }
    
    Gerente gerenteActual;
    public void setUsuarioActual(Gerente gerente) {
        this.gerenteActual = gerente;
        mv.setGerente(gerente);
    }
    
    public void seleccionarMenu(JPanel panel) {

        panelSeleccionado = panel;
        JPanel[] paneles = {
            pnlInicio,
            pnlEmpleados,
            pnlMetasVentas,
            pnlReporteCancelaciones,
            pnlReporteFinanciero,
            pnlTarifas,
            pnlMargenUtilidad
        };

        for(int j = 0; j < paneles.length; j++){
            paneles[j].setBackground(Color.WHITE);
        }

        if (expandido && panelSeleccionado != null) {
        panelSeleccionado.setBackground(new Color(255,170,44));
        }
    }
    void mostrarPanel(JPanel panelVisible){

        JPanel[] paneles = {i,e,mv,r,rf,t,mu};

        for(int j = 0; j < paneles.length; j++){
            JPanel panel = paneles[j];
            panel.setVisible(false);
        }

        panelVisible.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        pnlInicio = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        pnlEmpleados = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnEmpleados = new javax.swing.JButton();
        pnlReporteCancelaciones = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnReporteCancelaciones = new javax.swing.JButton();
        pnlReporteFinanciero = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnReporteFinanciero = new javax.swing.JButton();
        pnlTarifas = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnTarifas = new javax.swing.JButton();
        pnlCerrarSesion = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        pnlMetasVentas = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnMetasVentas = new javax.swing.JButton();
        pnlMargenUtilidad = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnMargenUtilidad = new javax.swing.JButton();
        lypPrincipal = new javax.swing.JLayeredPane();

        setLayout(new java.awt.BorderLayout());

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono1.png"))); // NOI18N

        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(64, 48, 0));
        btnMenu.setText("...");
        btnMenu.setAutoscrolls(true);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setFocusPainted(false);
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        pnlInicio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/inicio.png"))); // NOI18N

        btnInicio.setText("Inicio    ");
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(btnInicio))
                .addContainerGap())
        );

        pnlEmpleados.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/clientes.png"))); // NOI18N

        btnEmpleados.setText("Empleados");
        btnEmpleados.setBorderPainted(false);
        btnEmpleados.setContentAreaFilled(false);
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleados.setFocusPainted(false);
        btnEmpleados.addActionListener(this::btnEmpleadosActionPerformed);

        javax.swing.GroupLayout pnlEmpleadosLayout = new javax.swing.GroupLayout(pnlEmpleados);
        pnlEmpleados.setLayout(pnlEmpleadosLayout);
        pnlEmpleadosLayout.setHorizontalGroup(
            pnlEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpleados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEmpleadosLayout.setVerticalGroup(
            pnlEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpleadosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(btnEmpleados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlReporteCancelaciones.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar-documento.png"))); // NOI18N

        btnReporteCancelaciones.setText("Reporte de cancelaciones");
        btnReporteCancelaciones.setBorderPainted(false);
        btnReporteCancelaciones.setContentAreaFilled(false);
        btnReporteCancelaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteCancelaciones.setFocusPainted(false);
        btnReporteCancelaciones.addActionListener(this::btnReporteCancelacionesActionPerformed);

        javax.swing.GroupLayout pnlReporteCancelacionesLayout = new javax.swing.GroupLayout(pnlReporteCancelaciones);
        pnlReporteCancelaciones.setLayout(pnlReporteCancelacionesLayout);
        pnlReporteCancelacionesLayout.setHorizontalGroup(
            pnlReporteCancelacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReporteCancelacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteCancelaciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlReporteCancelacionesLayout.setVerticalGroup(
            pnlReporteCancelacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReporteCancelacionesLayout.createSequentialGroup()
                .addGroup(pnlReporteCancelacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReporteCancelacionesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel16))
                    .addGroup(pnlReporteCancelacionesLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnReporteCancelaciones)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlReporteFinanciero.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/archivo-factura-dolar.png"))); // NOI18N

        btnReporteFinanciero.setText("Reporte financiero");
        btnReporteFinanciero.setBorderPainted(false);
        btnReporteFinanciero.setContentAreaFilled(false);
        btnReporteFinanciero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteFinanciero.setFocusPainted(false);
        btnReporteFinanciero.addActionListener(this::btnReporteFinancieroActionPerformed);

        javax.swing.GroupLayout pnlReporteFinancieroLayout = new javax.swing.GroupLayout(pnlReporteFinanciero);
        pnlReporteFinanciero.setLayout(pnlReporteFinancieroLayout);
        pnlReporteFinancieroLayout.setHorizontalGroup(
            pnlReporteFinancieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReporteFinancieroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteFinanciero)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlReporteFinancieroLayout.setVerticalGroup(
            pnlReporteFinancieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReporteFinancieroLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlReporteFinancieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporteFinanciero)
                    .addComponent(jLabel14))
                .addGap(8, 8, 8))
        );

        pnlTarifas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tarifa.png"))); // NOI18N

        btnTarifas.setText("Tarifas");
        btnTarifas.setBorderPainted(false);
        btnTarifas.setContentAreaFilled(false);
        btnTarifas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTarifas.setFocusPainted(false);
        btnTarifas.addActionListener(this::btnTarifasActionPerformed);

        javax.swing.GroupLayout pnlTarifasLayout = new javax.swing.GroupLayout(pnlTarifas);
        pnlTarifas.setLayout(pnlTarifasLayout);
        pnlTarifasLayout.setHorizontalGroup(
            pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarifasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTarifas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTarifasLayout.setVerticalGroup(
            pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarifasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(btnTarifas))
                .addGap(8, 8, 8))
        );

        pnlCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir.png"))); // NOI18N

        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        javax.swing.GroupLayout pnlCerrarSesionLayout = new javax.swing.GroupLayout(pnlCerrarSesion);
        pnlCerrarSesion.setLayout(pnlCerrarSesionLayout);
        pnlCerrarSesionLayout.setHorizontalGroup(
            pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCerrarSesionLayout.setVerticalGroup(
            pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerrarSesionLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(btnCerrarSesion))
                .addGap(9, 9, 9))
        );

        pnlMetasVentas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/objetivos.png"))); // NOI18N

        btnMetasVentas.setText("Metas de ventas");
        btnMetasVentas.setBorderPainted(false);
        btnMetasVentas.setContentAreaFilled(false);
        btnMetasVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMetasVentas.setFocusPainted(false);
        btnMetasVentas.addActionListener(this::btnMetasVentasActionPerformed);

        javax.swing.GroupLayout pnlMetasVentasLayout = new javax.swing.GroupLayout(pnlMetasVentas);
        pnlMetasVentas.setLayout(pnlMetasVentasLayout);
        pnlMetasVentasLayout.setHorizontalGroup(
            pnlMetasVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMetasVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMetasVentas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMetasVentasLayout.setVerticalGroup(
            pnlMetasVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMetasVentasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlMetasVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMetasVentas)
                    .addComponent(jLabel17))
                .addGap(8, 8, 8))
        );

        pnlMargenUtilidad.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/grafico-circular-simple-circulo-dolar.png"))); // NOI18N

        btnMargenUtilidad.setText("Margen de utilidad");
        btnMargenUtilidad.setBorderPainted(false);
        btnMargenUtilidad.setContentAreaFilled(false);
        btnMargenUtilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMargenUtilidad.setFocusPainted(false);
        btnMargenUtilidad.addActionListener(this::btnMargenUtilidadActionPerformed);

        javax.swing.GroupLayout pnlMargenUtilidadLayout = new javax.swing.GroupLayout(pnlMargenUtilidad);
        pnlMargenUtilidad.setLayout(pnlMargenUtilidadLayout);
        pnlMargenUtilidadLayout.setHorizontalGroup(
            pnlMargenUtilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMargenUtilidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMargenUtilidad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMargenUtilidadLayout.setVerticalGroup(
            pnlMargenUtilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMargenUtilidadLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlMargenUtilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(btnMargenUtilidad))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMetasVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlReporteCancelaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlReporteFinanciero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTarifas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMargenUtilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMetasVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlReporteCancelaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlReporteFinanciero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTarifas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMargenUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(pnlCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlMenu, java.awt.BorderLayout.LINE_START);

        lypPrincipal.setLayout(new java.awt.CardLayout());
        add(lypPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        expandido = !expandido;

        if (expandido) {
            pnlMenu.setPreferredSize(new Dimension(220, pnlMenu.getHeight()));
        } else {
            pnlMenu.setPreferredSize(new Dimension(50, pnlMenu.getHeight()));
        }

        seleccionarMenu(panelSeleccionado);

        pnlMenu.revalidate();
        pnlMenu.repaint();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlInicio);
        mostrarPanel(i);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlEmpleados);
        mostrarPanel(e);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnMetasVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetasVentasActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlMetasVentas);
        mostrarPanel(mv);
    }//GEN-LAST:event_btnMetasVentasActionPerformed

    private void btnReporteCancelacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteCancelacionesActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlReporteCancelaciones);
        mostrarPanel(r);
    }//GEN-LAST:event_btnReporteCancelacionesActionPerformed

    private void btnReporteFinancieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteFinancieroActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlReporteFinanciero);
        mostrarPanel(rf);
    }//GEN-LAST:event_btnReporteFinancieroActionPerformed

    private void btnTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarifasActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlTarifas);
        mostrarPanel(t);
    }//GEN-LAST:event_btnTarifasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventana =(VentanaPrincipal) SwingUtilities.getWindowAncestor(this);
        ventana.volverInicio();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnMargenUtilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMargenUtilidadActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlMargenUtilidad);
        mostrarPanel(mu);
    }//GEN-LAST:event_btnMargenUtilidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMargenUtilidad;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMetasVentas;
    private javax.swing.JButton btnReporteCancelaciones;
    private javax.swing.JButton btnReporteFinanciero;
    private javax.swing.JButton btnTarifas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLayeredPane lypPrincipal;
    private javax.swing.JPanel pnlCerrarSesion;
    private javax.swing.JPanel pnlEmpleados;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlMargenUtilidad;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMetasVentas;
    private javax.swing.JPanel pnlReporteCancelaciones;
    private javax.swing.JPanel pnlReporteFinanciero;
    private javax.swing.JPanel pnlTarifas;
    // End of variables declaration//GEN-END:variables
}
