/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesAsesorVentas;

import PanelesGenerales.Pasajeros;
import cristorey_ef.PaqueteTuristicoControlador;
import cristorey_ef.PasajeroControlador;
import cristorey_ef.ReservaControlador;
import cristorey_ef.UsuarioControlador;
import cristorey_ef.VentanaPrincipal;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipalAsesor extends javax.swing.JPanel {

    /**
     * Creates new form PantallaAdministrador
     */
    Inicio i;
    AsignarGuia ag;
    AprobarReservas ar;
    CatalogoDestino cd;
    Pasajeros p;
    
    private JPanel panelSeleccionado;
    private boolean expandido = false;
    public VentanaPrincipalAsesor(UsuarioControlador uc, PasajeroControlador pc,
            ReservaControlador rc, PaqueteTuristicoControlador ptc) {
        initComponents();
        
        i = new Inicio(ptc, uc);
        ag = new AsignarGuia(uc, ptc);
        ar = new AprobarReservas(rc);
        cd = new CatalogoDestino(uc,ptc);
        p = new Pasajeros(pc, rc);
        
        
        pnlMenu.setPreferredSize(new Dimension(50, pnlMenu.getHeight()));
        pnlMenu.revalidate();
        JPanel[] paneles = {i,ag, ar, cd, p};

        for(int j = 0; j < paneles.length; j++){
            JPanel panel = paneles[j];
            lypPrincipal.add(panel);
        }

        mostrarPanel(i);
        seleccionarMenu(pnlInicio);
    }
    
    public void seleccionarMenu(JPanel panel) {

        panelSeleccionado = panel;
        JPanel[] paneles = {
            pnlInicio,
            pnlAprobarReservas,
            pnlAsignarGuias,
            pnlCatalogoDestino,
            pnlPasajeros
        };

         for(int j = 0; j < paneles.length; j++){
            panel.setBackground(Color.WHITE);
        }

        if (expandido && panelSeleccionado != null) {
        panelSeleccionado.setBackground(new Color(255,170,44));
        }
    }
    void mostrarPanel(JPanel panelVisible){

        JPanel[] paneles = {i, ag, ar, cd, p};

       for(int j = 0; j < paneles.length; j++){
            JPanel panel = paneles[j];
            panel.setVisible(false);
        }

        panelVisible.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        pnlInicio = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        pnlCerrarSesion = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        pnlAprobarReservas = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnAprobarReservas = new javax.swing.JButton();
        pnlAsignarGuias = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnAsignarGuias = new javax.swing.JButton();
        pnlCatalogoDestino = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnCatalogoDestino = new javax.swing.JButton();
        pnlPasajeros = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnPasajeros = new javax.swing.JButton();
        lypPrincipal = new javax.swing.JLayeredPane();

        setLayout(new java.awt.BorderLayout());

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono1.png"))); // NOI18N

        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(64, 48, 0));
        btnMenu.setText("...");
        btnMenu.setAutoscrolls(true);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setFocusPainted(false);
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        pnlInicio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/inicio.png"))); // NOI18N

        btnInicio.setText("Inicio    ");
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(btnInicio))
                .addContainerGap())
        );

        pnlCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir.png"))); // NOI18N

        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        javax.swing.GroupLayout pnlCerrarSesionLayout = new javax.swing.GroupLayout(pnlCerrarSesion);
        pnlCerrarSesion.setLayout(pnlCerrarSesionLayout);
        pnlCerrarSesionLayout.setHorizontalGroup(
            pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCerrarSesionLayout.setVerticalGroup(
            pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerrarSesionLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(btnCerrarSesion))
                .addGap(9, 9, 9))
        );

        pnlAprobarReservas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/viaje-en-coche.png"))); // NOI18N

        btnAprobarReservas.setText("Aprobar reservas");
        btnAprobarReservas.setBorderPainted(false);
        btnAprobarReservas.setContentAreaFilled(false);
        btnAprobarReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAprobarReservas.setFocusPainted(false);
        btnAprobarReservas.addActionListener(this::btnAprobarReservasActionPerformed);

        javax.swing.GroupLayout pnlAprobarReservasLayout = new javax.swing.GroupLayout(pnlAprobarReservas);
        pnlAprobarReservas.setLayout(pnlAprobarReservasLayout);
        pnlAprobarReservasLayout.setHorizontalGroup(
            pnlAprobarReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAprobarReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAprobarReservas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAprobarReservasLayout.setVerticalGroup(
            pnlAprobarReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAprobarReservasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlAprobarReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAprobarReservas)
                    .addComponent(jLabel17))
                .addGap(8, 8, 8))
        );

        pnlAsignarGuias.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/viaje-en-coche.png"))); // NOI18N

        btnAsignarGuias.setText("Asignar guias");
        btnAsignarGuias.setBorderPainted(false);
        btnAsignarGuias.setContentAreaFilled(false);
        btnAsignarGuias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsignarGuias.setFocusPainted(false);
        btnAsignarGuias.addActionListener(this::btnAsignarGuiasActionPerformed);

        javax.swing.GroupLayout pnlAsignarGuiasLayout = new javax.swing.GroupLayout(pnlAsignarGuias);
        pnlAsignarGuias.setLayout(pnlAsignarGuiasLayout);
        pnlAsignarGuiasLayout.setHorizontalGroup(
            pnlAsignarGuiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsignarGuiasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsignarGuias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAsignarGuiasLayout.setVerticalGroup(
            pnlAsignarGuiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsignarGuiasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlAsignarGuiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAsignarGuias)
                    .addComponent(jLabel18))
                .addGap(8, 8, 8))
        );

        pnlCatalogoDestino.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/viaje-en-coche.png"))); // NOI18N

        btnCatalogoDestino.setText("Catalogo de destinos");
        btnCatalogoDestino.setBorderPainted(false);
        btnCatalogoDestino.setContentAreaFilled(false);
        btnCatalogoDestino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatalogoDestino.setFocusPainted(false);
        btnCatalogoDestino.addActionListener(this::btnCatalogoDestinoActionPerformed);

        javax.swing.GroupLayout pnlCatalogoDestinoLayout = new javax.swing.GroupLayout(pnlCatalogoDestino);
        pnlCatalogoDestino.setLayout(pnlCatalogoDestinoLayout);
        pnlCatalogoDestinoLayout.setHorizontalGroup(
            pnlCatalogoDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCatalogoDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCatalogoDestino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCatalogoDestinoLayout.setVerticalGroup(
            pnlCatalogoDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCatalogoDestinoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlCatalogoDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCatalogoDestino)
                    .addComponent(jLabel19))
                .addGap(8, 8, 8))
        );

        pnlPasajeros.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/clientes.png"))); // NOI18N

        btnPasajeros.setText(" Pasajeros");
        btnPasajeros.setBorderPainted(false);
        btnPasajeros.setContentAreaFilled(false);
        btnPasajeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPasajeros.setFocusPainted(false);
        btnPasajeros.addActionListener(this::btnPasajerosActionPerformed);

        javax.swing.GroupLayout pnlPasajerosLayout = new javax.swing.GroupLayout(pnlPasajeros);
        pnlPasajeros.setLayout(pnlPasajerosLayout);
        pnlPasajerosLayout.setHorizontalGroup(
            pnlPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasajerosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPasajeros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPasajerosLayout.setVerticalGroup(
            pnlPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasajerosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(btnPasajeros))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlAprobarReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlAsignarGuias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCatalogoDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAprobarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAsignarGuias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCatalogoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(pnlCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        add(pnlMenu, java.awt.BorderLayout.LINE_START);

        lypPrincipal.setLayout(new java.awt.CardLayout());
        add(lypPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        expandido = !expandido;

        if (expandido) {
            pnlMenu.setPreferredSize(new Dimension(220, pnlMenu.getHeight()));
        } else {
            pnlMenu.setPreferredSize(new Dimension(50, pnlMenu.getHeight()));
        }

        seleccionarMenu(panelSeleccionado);

        pnlMenu.revalidate();
        pnlMenu.repaint();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlInicio);
        mostrarPanel(i);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnAprobarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobarReservasActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlAprobarReservas);
        ar.cargarTabla();
        mostrarPanel(ar);
    }//GEN-LAST:event_btnAprobarReservasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventana =(VentanaPrincipal) SwingUtilities.getWindowAncestor(this);
        ventana.volverInicio();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnAsignarGuiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarGuiasActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlAsignarGuias);
        ag.cargar();
        mostrarPanel(ag);
    }//GEN-LAST:event_btnAsignarGuiasActionPerformed

    private void btnCatalogoDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoDestinoActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlCatalogoDestino);
        mostrarPanel(cd);
    }//GEN-LAST:event_btnCatalogoDestinoActionPerformed

    private void btnPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasajerosActionPerformed
        // TODO add your handling code here:
        seleccionarMenu(pnlPasajeros);
        mostrarPanel(p);
    }//GEN-LAST:event_btnPasajerosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprobarReservas;
    private javax.swing.JButton btnAsignarGuias;
    private javax.swing.JButton btnCatalogoDestino;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPasajeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLayeredPane lypPrincipal;
    private javax.swing.JPanel pnlAprobarReservas;
    private javax.swing.JPanel pnlAsignarGuias;
    private javax.swing.JPanel pnlCatalogoDestino;
    private javax.swing.JPanel pnlCerrarSesion;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPasajeros;
    // End of variables declaration//GEN-END:variables
}
