/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cristorey_ef;

import PanelesAdministrador.VentanaPrincipalAdmin;
import PanelesPlanillero.VentanaPrincipalPlani;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    /**
     * Creates new form PantallaPrincipal
     */
    private final UsuarioControlador usuarioControlador;
    private final PasajeroControlador pasajeroControlador;
    private final ReservaControlador reservaControlador;
    private final PaqueteTuristicoControlador paqueteTuristicoControlador;
    
    Container contenidoOriginal;
    VentanaPrincipalAdmin admin;
    VentanaPrincipalPlani plani;
    public VentanaPrincipal(PasajeroControlador pasajeroControlador,
        UsuarioControlador usuarioControlador,
        ReservaControlador reservaControlador,
        PaqueteTuristicoControlador paqueteTuristicoControlador) {
        initComponents();
        this.pasajeroControlador = pasajeroControlador;
        this.usuarioControlador = usuarioControlador;
        this.reservaControlador = reservaControlador;
        this.paqueteTuristicoControlador = paqueteTuristicoControlador;
        contenidoOriginal = getContentPane();
        admin = new VentanaPrincipalAdmin(usuarioControlador, pasajeroControlador,
                reservaControlador, paqueteTuristicoControlador);
        plani = new VentanaPrincipalPlani(pasajeroControlador, usuarioControlador,
                reservaControlador, paqueteTuristicoControlador);
    }
    
    public UsuarioControlador getUsuarioControlador() {
        return usuarioControlador;
    }

    public PasajeroControlador getPasajeroControlador() {
        return pasajeroControlador;
    }

    public ReservaControlador getReservaControlador() {
        return reservaControlador;
    }
    
    public PaqueteTuristicoControlador getPaqueteTuristicoControlador() {
        return paqueteTuristicoControlador;
    }

    public VentanaPrincipalAdmin getAdmin() {
        return admin;
    }

    public VentanaPrincipalPlani getPlani() {
        return plani;
    }
    
    public void navegar(JPanel panel) {

        this.setContentPane(panel);
        this.revalidate();
        this.repaint();
    }
    public void volverInicio(){

        setContentPane(contenidoOriginal);

        revalidate();
        repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRIISTO REY TRAVEL");

        panel.setMinimumSize(new java.awt.Dimension(1000, 600));
        panel.setOpaque(false);
        panel.setPreferredSize(new java.awt.Dimension(1000, 600));
        panel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(105, 41, 0, 0);
        panel.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("¡Bienvenido!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 53, 0, 0);
        panel.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel3.setText("Inicia sesión para continuar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 30, 0, 0);
        panel.add(jLabel3, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuario.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 318, 0, 0);
        panel.add(jLabel4, gridBagConstraints);

        btnIngresar.setBackground(new java.awt.Color(255, 153, 51));
        btnIngresar.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 69, 56, 0);
        panel.add(btnIngresar, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 318, 0, 0);
        panel.add(jLabel5, gridBagConstraints);

        txtCorreo.setMaximumSize(new java.awt.Dimension(100, 30));
        txtCorreo.setMinimumSize(new java.awt.Dimension(100, 30));
        txtCorreo.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 334);
        panel.add(txtCorreo, gridBagConstraints);

        txtClave.setActionCommand("<Not Set>");
        txtClave.setMaximumSize(new java.awt.Dimension(100, 30));
        txtClave.setMinimumSize(new java.awt.Dimension(100, 30));
        txtClave.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 334);
        panel.add(txtClave, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        String correo = txtCorreo.getText();
        String clave = txtClave.getText();

        Usuario encontrado = null;

        for (Usuario u : usuarioControlador.getUsuario()) {
            if (u.validarAcceso(correo, clave)) {
                encontrado = u;
                break;
            }
        }

        if (encontrado == null) {
            JOptionPane.showMessageDialog(this,"Credenciales incorrectas");
        }else if (encontrado.isBloqueado()) {
        JOptionPane.showMessageDialog(this, "Tu cuenta ha sido bloqueada. Contacta al administrador del sistema.",
            "Acceso bloqueado", JOptionPane.WARNING_MESSAGE);
        } else if (encontrado instanceof Administrador) {
            navegar(admin);
        } else if (encontrado instanceof Planillero) {
            navegar(plani);
        }
        txtCorreo.setText("");
        txtClave.setText("");
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        PasajeroControlador pasajeroControlador = new PasajeroControlador();
        UsuarioControlador usuarioControlador = new UsuarioControlador();
        ReservaControlador reservaControlador = new ReservaControlador();
        PaqueteTuristicoControlador paqueteTuristicoControlador = new PaqueteTuristicoControlador();

        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal(pasajeroControlador,
                usuarioControlador, reservaControlador, paqueteTuristicoControlador).setVisible(true));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel{
        private Image imagen;

        public FondoPanel() {
            java.net.URL imgUrl = getClass().getResource("/Iconos/Fondo.png");
            if (imgUrl != null) {
                this.imagen = new ImageIcon(imgUrl).getImage();
            }
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (imagen != null) {
                Graphics2D g2d = (Graphics2D) g;
            
                g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
                g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                g2d.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            }   
        }
    }
}
